---
- name: install etcd and kubernetes from the virt7-docker-common-release repo
  yum:
    name: "{{ item }}"
    enablerepo: virt7-docker-common-release
    state: present
    update_cache: true
  with_items:
    - kubernetes
    - docker

- name: copy kubernetes config file
  copy:
    src: config
    dest: /etc/kubernetes
    owner: root
    group: wheel
    mode: 0644
