---
- name: install etcd and kubernetes from the virt7-docker-common-release repo
  yum:
    name: "{{ item }}"
    enablerepo: virt7-docker-common-release
    state: present
    update_cache: true
  with_items:
    - kubernetes
    - docker

- name: copy kubernetes config file
  copy:
    src: config
    dest: /etc/kubernetes
    owner: root
    group: wheel
    mode: 0644

- name: copy kublet template file
  template:
    src: kublet.j2
    dest: /etc/kubernetes/kubelet
    owner: root
    group: root
    mode: 0644

- name: enable and start kubernetes minion services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: True
  with_items:
    - kube-proxy
    - kubelet
    - docker
