---

- name: copy etcd config file
  copy:
    src: etcd.conf
    dest: /etc/etcd
    owner: root
    group: wheel
    mode: 0644

- name: enable and start etcd service
  systemd:
    name: etcd
    state: started
    enabled: True

