apiVersion: v1
kind: Service
metadata:
  name: red-service
spec:
  selector:
    colour: red
  type: NodePort
  ports:
  - name: red-service-ports
    port: 8888 		# The port the service listens on inside the cluster (used by internal consumers)
    nodePort: 31001 	# The external port on which the service can be contacted
    targetPort: 8080 	# The container port
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: green-service
spec:
  selector:
    colour: green
  type: NodePort
  ports:
  - name: green-service-ports
    port: 8888 		# The port the service listens on inside the cluster (used by internal consumers)
    nodePort: 31002 	# The external port on which the service can be contacted
    targetPort: 8080 	# The container port
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: blue-service
spec:
  selector:
    colour: blue
  type: NodePort
  ports:
  - name: blue-service-ports
    port: 8888 		# The port the service listens on inside the cluster (used by internal consumers)
    nodePort: 31003 	# The external port on which the service can be contacted
    targetPort: 8080 	# The container port
    protocol: TCP
