
- hosts: all
  user: ubuntu
  gather_facts: False
  become: True

  tasks:
  - name: install python
    raw: "apt-get install -y python"

  - name: install git
    apt:
      name: git
      state: latest

  - name: install nfs client
    apt:
      name: nfs-common
      state: latest
