---

- hosts: all
  become: true
  roles:
    - common

- hosts: controller
  become: true
  roles:
    - etcd
    - kubernetes-master

- hosts: minions
  become: true
  roles:
    - kubernetes-minion

